# Generated by Django 3.2.25 on 2024-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
